apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: java-stage
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: gcp-sm-store
    kind: SecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: managed-argo-repo
      property: github_token
