apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
 - github-secret.yaml
 - script-config-map.yaml
 - post-sync-stage.yaml
commonLabels:
  purpose: Inception-demo
  env : stage

replicas:
 - name: productcatalogue
   count: 2 
 - name: shopfront
   count: 2

patches:
  - target:
      kind: Deployment
      name: productcatalogue
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '6255/productcatalouge-image:9fd63505820d569fce72cb76373d19506de867db'
  - target:
      kind: Deployment
      name: shopfront
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '6255/shopfront-image:9fd63505820d569fce72cb76373d19506de867db'

