apiVersion: batch/v1
kind: Job
metadata:
   name: postsync-test
   annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
   backoffLimit: 3
   template:
     spec:
       restartPolicy: OnFailure
       containers:
          - name: postsycn-test
            image: 6255/curl:1.0
            command: ["bash","/script/status_test.sh"]
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                   secretKeyRef:
                      name: github-token
                      key: token
            volumeMounts:
               - name: script
                 mountPath: /script
       volumes:
          - name: script
            configMap:
              name: post-sync-script
              items:
               - key: status_test.sh
                 path: status_test.sh
              defaultMode: 0755
